# Generated by Django 3.0.2 on 2020-01-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Область поиска')),
            ],
            options={
                'verbose_name': 'Область поиска',
                'verbose_name_plural': 'Области поиска',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.TextField(verbose_name='Запрос')),
                ('result', models.TextField(verbose_name='Результат')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'Истории поисков',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('search_history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_v1.SearchHistory', verbose_name='История поиска')),
            ],
            options={
                'verbose_name': 'Пользователь Бота',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
