# Generated by Django 3.0.2 on 2020-01-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_v1', '0002_auto_20200131_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='search_history',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='bot_v1.SearchHistory', verbose_name='История поиска'),
        ),
    ]
